version: '3.7'

services:

  naming-server:
    image: naming-server:latest
    mem_limit: 500m
    ports:
      - "8761:8761"

  bank-account:
    image: bank-account:latest
    build: bankAccountService
    mem_limit: 500m
    ports:
      - "8200:8200"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

  crypto-wallet:
    image: crypto-wallet:latest
    build: CryptoWallet
    mem_limit: 500m
    ports:
      - "8300:8300"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

  crypto-exchange:
    image: crypto-exchange:latest
    build: CryptoExchange
    mem_limit: 500m
    ports:
      - "8400:8400"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

  crypto-conversion:
    image: crypto-conversion:latest
    build: CryptoConversion
    mem_limit: 500m
    ports:
      - "8500:8500"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

  currency-exchange:
    image: currency-exchange:latest
    build: CurrencyExchange
    mem_limit: 500m
    ports:
      - "8000:8000"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'


  currency-conversion:
    image: currency-conversion:latest
    build: CurrencyConversion
    mem_limit: 500m
    ports:
      - "8100:8100"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

  trade-service:
    image: trade-service:latest
    build: Trade
    mem_limit: 500m
    ports:
      - "8600:8600"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

  users-service:
    image: users-service:latest
    build: UsersService
    mem_limit: 500m
    ports:
      - "8770:8770"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8770/users"]
      interval: 30s
      timeout: 30s
      retries: 5
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

  api-gateway:
    image: api-gateway:latest
    build: ApiGateway
    mem_limit: 500m
    depends_on:
      users-service: 
        condition: service_healthy
    ports:
      - "8765:8765"
    
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://host.docker.internal:8761/eureka"}}}}'

networks:
  soas-network: